#!/usr/bin/env python
"""Generate the cpl_bypass forcing-diagnostic SourceMods file.

Reads lnd_import_export.F90 from the pinned E3SM commit and inserts four
diagnostic blocks, then writes the result to a case's SourceMods/src.elm/.
Refuses to write if any anchor is missing or ambiguous, so it cannot silently
produce a half-patched file when the shared tree moves.

The diagnostic answers, for one gridcell, what the reader actually did:

  DIAG_INIT    the initialization path: per variable, the index pair it
               computed and the array bounds it computed them against
  DIAG_PRE     the per-timestep index pair BEFORE the end-of-record guard
  DIAG_POST    the same pair AFTER the guard, so whether the guard fired is
               recorded rather than inferred from control flow
  DIAG_READ    the two read endpoints: index, raw packed short and decoded
               value at each of t1 and t2
  DIAG_INTP    the interpolation intermediates: weights, the blended value,
               and the per-month var_mult/var_offset that will be applied
  DIAG_FORC    the actual forcing handed to ELM (state)
  DIAG_FLUX    the actual forcing handed to ELM (fluxes)

Why DIAG_READ/DIAG_INTP/DIAG_FORC are three blocks and not one
--------------------------------------------------------------
An earlier draft printed the blend and labelled it "used".  That is wrong for
most of the seven variables, so it would have made a wrong end-point verdict
look verified:

  * forc_t / forc_th / forc_pbot / forc_q apply var_mult(v,g,mon) and
    var_offset(v,g,mon) to the blend and then clamp -- min(...,323) for T,
    max(...) for pbot and q.
  * FSDS is not interpolated between two endpoints at all.  Only tindex(4,2)
    is read, scaled by wt2(4) (which the cosz branch overwrites), then split
    into forc_solad/forc_solai by the ratio_rvrf polynomial.
  * PRECTmms is not interpolated either -- the source says so outright
    ("Don't interpolate rainfall data") -- and is then split into
    rainc/rainl/snowc/snowl by a temperature ramp and a 0.1/0.9 split.
  * forc_lwrad can be discarded entirely and recomputed as ea*STEBOL*tbot**4.

So the blend equals the forcing for none of FSDS, PRECTmms, FLDS and only
up to var_mult/var_offset/clamping for the rest.  Reading the endpoints back
against the input file needs DIAG_READ; judging what the model actually ran
on needs DIAG_FORC/DIAG_FLUX; the step between them is DIAG_INTP.

Gating (this is the part that the first draft got wrong)
-------------------------------------------------------
Two independent gates, OR'd, neither keyed on the index value:

  * the first DIAG_FIRST_N import calls of THIS process.  Keyed on a saved
    counter, not on nstep -- after a continuation restart nstep is already
    large, so an nstep<=N gate would record nothing at exactly the restart
    that is being tested.

  * any model date inside a configured window.  Windows are inclusive
    YYYYMMDD ranges, set per test (restart date, end-of-run date).  Keyed on
    the date, not on tindex: a gate like "tindex > timelen-16" goes false the
    moment the index wraps, which is precisely the event worth recording.

Volume: masterproc and g == bounds%begg only, 4 blocks x 7 variables per
recorded call.  A 24-call window is a few hundred lines.

Usage:
    make_diag_sourcemod.py --src <lnd_import_export.F90 from pinned commit> \
                           --out <CASEROOT>/SourceMods/src.elm/lnd_import_export.F90 \
                           --first-n 24 --window 20241231-20250102 [--window ...]
"""
import argparse
import sys

DECL_ANCHOR = "    integer ::  met_nvars, nyears_spinup, nyears_trans, starti_site, endi_site"

INIT_ANCHOR = "          end do    !end variable loop"

PRE_ANCHOR = "            if (const_climate_hist .or. yr .le. atm2lnd_vars%startyear_met) then"

POST_ANCHOR = """            !if (yr .gt. atm2lnd_vars%startyear_met) then """

READ_ANCHOR = "        !Air temperature"

FORC_ANCHOR = ("  !------------------------------------Fire data "
               "-------------------------------------------------------")


def decl_block(first_n, windows):
    lo = ", ".join(str(w[0]) for w in windows)
    hi = ", ".join(str(w[1]) for w in windows)
    return """    ! --- forcing diagnostic (SourceMods; generated by make_diag_sourcemod.py) ---
    integer, save :: diag_ncall = 0
    integer :: diag_ymd, diag_iw
    logical :: diag_on
    real(r8) :: diag_d1, diag_d2
    integer, parameter :: DIAG_FIRST_N = {first_n}
    integer, parameter :: DIAG_NWIN = {nwin}
    integer, parameter :: DIAG_WIN_LO(DIAG_NWIN) = (/ {lo} /)
    integer, parameter :: DIAG_WIN_HI(DIAG_NWIN) = (/ {hi} /)
    ! --- end forcing diagnostic ---
""".format(first_n=first_n, nwin=len(windows), lo=lo, hi=hi)


GATE_BLOCK = """
            ! --- forcing diagnostic: evaluate the gate once per (gridcell, call) ---
            ! Both insertion sites sit inside "do g = begg,endg / do v = 1,nvars",
            ! so the counter must advance once per call, not once per gridcell,
            ! and diag_on must be recomputed for every g (it is false for all
            ! but begg).  Counting per gridcell would exhaust DIAG_FIRST_N in
            ! the first timestep.
            if (v .eq. 1) then
              if (g .eq. bounds%begg) diag_ncall = diag_ncall + 1
              diag_on = masterproc .and. (g .eq. bounds%begg) .and. &
                        (diag_ncall .le. DIAG_FIRST_N)
              if (masterproc .and. (g .eq. bounds%begg)) then
                diag_ymd = yr*10000 + mon*100 + day
                do diag_iw = 1, DIAG_NWIN
                  if (diag_ymd .ge. DIAG_WIN_LO(diag_iw) .and. &
                      diag_ymd .le. DIAG_WIN_HI(diag_iw)) diag_on = .true.
                end do
              end if
            end if
            ! --- end forcing diagnostic ---
"""

INIT_BLOCK = """            ! --- forcing diagnostic ---
            if (diag_on) then
              write(iulog,'(a,i6,a,i3,1x,a8,a,i9,a,i3,a,i3,a,i6,a,i10,a,i10,a,i10,a,i10)') &
                'DIAG_INIT call=', diag_ncall, ' v=', v, trim(metvars(v)), &
                ' ymd=', yr*10000+mon*100+day, ' tod_h=', tod/3600, &
                ' npf=', nint(atm2lnd_vars%npf(v)), ' tres=', nint(atm2lnd_vars%timeres(v)), &
                ' t1=', atm2lnd_vars%tindex(g,v,1), ' t2=', atm2lnd_vars%tindex(g,v,2), &
                ' timelen=', atm2lnd_vars%timelen(v), ' tl_spinup=', atm2lnd_vars%timelen_spinup(v)
            end if
            ! --- end forcing diagnostic ---
"""

PRE_BLOCK = """            ! --- forcing diagnostic: index pair BEFORE the guard ---
            if (diag_on) then
              write(iulog,'(a,i6,a,i3,1x,a8,a,i9,a,i6,a,i10,a,i10)') &
                'DIAG_PRE  call=', diag_ncall, ' v=', v, trim(metvars(v)), &
                ' ymd=', yr*10000+mon*100+day, ' tod_h=', tod/3600, &
                ' t1=', atm2lnd_vars%tindex(g,v,1), ' t2=', atm2lnd_vars%tindex(g,v,2)
            end if
            ! --- end forcing diagnostic ---
"""

POST_BLOCK = """            ! --- forcing diagnostic: index pair AFTER the guard ---
            if (diag_on) then
              write(iulog,'(a,i6,a,i3,1x,a8,a,i10,a,i10,a,i10)') &
                'DIAG_POST call=', diag_ncall, ' v=', v, trim(metvars(v)), &
                ' t1=', atm2lnd_vars%tindex(g,v,1), ' t2=', atm2lnd_vars%tindex(g,v,2), &
                ' timelen=', atm2lnd_vars%timelen(v)
            end if
            ! --- end forcing diagnostic ---
"""

READ_BLOCK = """        ! --- forcing diagnostic: read endpoints, then interpolation intermediates ---
        ! Neither of these is the forcing ELM runs on; see DIAG_FORC/DIAG_FLUX.
        if (diag_on) then
          write(iulog,'(a,i6,a,i8,a,i8,a,i8,a,i9,a,i6)') &
            'DIAG_CELL call=', diag_ncall, ' g=', g, ' begg=', bounds%begg, &
            ' endg=', bounds%endg, ' ymd=', yr*10000+mon*100+day, ' tod_h=', tod/3600
          do diag_iw = 1, met_nvars
            diag_d1 = atm2lnd_vars%atm_input(diag_iw,g,1,tindex(diag_iw,1))* &
                      atm2lnd_vars%scale_factors(diag_iw)+atm2lnd_vars%add_offsets(diag_iw)
            diag_d2 = atm2lnd_vars%atm_input(diag_iw,g,1,tindex(diag_iw,2))* &
                      atm2lnd_vars%scale_factors(diag_iw)+atm2lnd_vars%add_offsets(diag_iw)
            write(iulog,'(a,i6,a,i3,1x,a8,a,i10,a,i8,a,es16.9,a,i10,a,i8,a,es16.9)') &
              'DIAG_READ call=', diag_ncall, ' v=', diag_iw, trim(metvars(diag_iw)), &
              ' t1=', tindex(diag_iw,1), &
              ' raw1=', atm2lnd_vars%atm_input(diag_iw,g,1,tindex(diag_iw,1)), &
              ' dec1=', diag_d1, &
              ' t2=', tindex(diag_iw,2), &
              ' raw2=', atm2lnd_vars%atm_input(diag_iw,g,1,tindex(diag_iw,2)), &
              ' dec2=', diag_d2
            write(iulog,'(a,i6,a,i3,1x,a8,a,f9.6,a,f9.6,a,es16.9,a,es13.6,a,es13.6,a,es14.7,a,es14.7)') &
              'DIAG_INTP call=', diag_ncall, ' v=', diag_iw, trim(metvars(diag_iw)), &
              ' wt1=', wt1(diag_iw), ' wt2=', wt2(diag_iw), &
              ' blend=', diag_d1*wt1(diag_iw) + diag_d2*wt2(diag_iw), &
              ' vmult=', atm2lnd_vars%var_mult(diag_iw,g,mon), &
              ' voff=', atm2lnd_vars%var_offset(diag_iw,g,mon), &
              ' scale=', atm2lnd_vars%scale_factors(diag_iw), &
              ' offset=', atm2lnd_vars%add_offsets(diag_iw)
          end do
        end if
        ! --- end forcing diagnostic ---

"""

FORC_BLOCK = """        ! --- forcing diagnostic: the values ELM actually runs on ---
        ! Placed after every forc_* assignment in this gridcell iteration and
        ! before the fire-data section.  forc_rain*/forc_snow* are still the
        ! locals here; they are summed into forc_rain_not_downscaled_grc later.
        if (diag_on) then
          write(iulog,'(a,i6,a,i8,a,es16.9,a,es16.9,a,es16.9,a,es16.9,a,es16.9)') &
            'DIAG_FORC call=', diag_ncall, ' g=', g, &
            ' T=', atm2lnd_vars%forc_t_not_downscaled_grc(g), &
            ' TH=', atm2lnd_vars%forc_th_not_downscaled_grc(g), &
            ' PBOT=', atm2lnd_vars%forc_pbot_not_downscaled_grc(g), &
            ' Q=', atm2lnd_vars%forc_q_not_downscaled_grc(g), &
            ' LWD=', atm2lnd_vars%forc_lwrad_not_downscaled_grc(g)
          write(iulog,'(a,i6,11(a,es16.9))') &
            'DIAG_FLUX call=', diag_ncall, &
            ' SOLAD1=', atm2lnd_vars%forc_solad_grc(g,1), &
            ' SOLAD2=', atm2lnd_vars%forc_solad_grc(g,2), &
            ' SOLAI1=', atm2lnd_vars%forc_solai_grc(g,1), &
            ' SOLAI2=', atm2lnd_vars%forc_solai_grc(g,2), &
            ' RAINC=', forc_rainc, ' RAINL=', forc_rainl, &
            ' SNOWC=', forc_snowc, ' SNOWL=', forc_snowl, &
            ' U=', atm2lnd_vars%forc_u_grc(g), ' V=', atm2lnd_vars%forc_v_grc(g), &
            ' HGT=', atm2lnd_vars%forc_hgt_grc(g)
        end if
        ! --- end forcing diagnostic ---

"""


def insert_before(lines, anchor, block, label, expect=1):
    hits = [i for i, l in enumerate(lines) if l.rstrip() == anchor.rstrip()]
    if len(hits) != expect:
        sys.exit("ANCHOR %s: expected %d match(es), found %d -- refusing to write"
                 % (label, expect, len(hits)))
    out = []
    for i, l in enumerate(lines):
        if i in hits:
            out.extend(block.splitlines(True))
        out.append(l)
    return out


def parse_window(s):
    lo, hi = s.split("-")
    return int(lo), int(hi)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--src", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--first-n", type=int, default=24)
    p.add_argument("--window", action="append", default=[],
                   help="inclusive YYYYMMDD-YYYYMMDD, repeatable")
    a = p.parse_args()

    windows = [parse_window(w) for w in a.window] or [(0, 0)]
    lines = open(a.src).readlines()

    if any("forcing diagnostic" in l for l in lines):
        sys.exit("source already contains a diagnostic block -- refusing to double-patch")

    lines = insert_before(lines, DECL_ANCHOR, decl_block(a.first_n, windows), "DECL")
    # gate + INIT both go just before the end of the initialization variable loop
    lines = insert_before(lines, INIT_ANCHOR, GATE_BLOCK + INIT_BLOCK, "INIT")
    lines = insert_before(lines, PRE_ANCHOR, GATE_BLOCK + PRE_BLOCK, "PRE")
    lines = insert_before(lines, POST_ANCHOR, POST_BLOCK, "POST")
    lines = insert_before(lines, READ_ANCHOR, READ_BLOCK, "READ")
    lines = insert_before(lines, FORC_ANCHOR, FORC_BLOCK, "FORC")

    with open(a.out, "w") as f:
        f.writelines(lines)
    print("wrote %s" % a.out)
    print("  first-n : %d import calls per process start" % a.first_n)
    print("  windows : %s" % windows)


if __name__ == "__main__":
    main()
