#!/usr/bin/env python
"""Generate the cpl_bypass forcing-diagnostic SourceMods file.

Reads lnd_import_export.F90 from the pinned E3SM commit and inserts four
diagnostic blocks, then writes the result to a case's SourceMods/src.elm/.
Refuses to write if any anchor is missing or ambiguous, so it cannot silently
produce a half-patched file when the shared tree moves.

The diagnostic answers, for one gridcell, what the reader actually did:

  DIAG_INIT    the initialization path: per variable, the index pair it
               computed and the array bounds it computed them against
  DIAG_PRE     the per-timestep index pair BEFORE the end-of-record guard
  DIAG_POST    the same pair AFTER the guard, so whether the guard fired is
               recorded rather than inferred from control flow
  DIAG_USE     what was actually read and used: raw packed shorts at both
               indices, scale_factor/add_offset, both decoded endpoints,
               the interpolation weights, and the blended value

Gating (this is the part that the first draft got wrong)
-------------------------------------------------------
Two independent gates, OR'd, neither keyed on the index value:

  * the first DIAG_FIRST_N import calls of THIS process.  Keyed on a saved
    counter, not on nstep -- after a continuation restart nstep is already
    large, so an nstep<=N gate would record nothing at exactly the restart
    that is being tested.

  * any model date inside a configured window.  Windows are inclusive
    YYYYMMDD ranges, set per test (restart date, end-of-run date).  Keyed on
    the date, not on tindex: a gate like "tindex > timelen-16" goes false the
    moment the index wraps, which is precisely the event worth recording.

Volume: masterproc and g == bounds%begg only, 4 blocks x 7 variables per
recorded call.  A 24-call window is a few hundred lines.

Usage:
    make_diag_sourcemod.py --src <lnd_import_export.F90 from pinned commit> \
                           --out <CASEROOT>/SourceMods/src.elm/lnd_import_export.F90 \
                           --first-n 24 --window 20241231-20250102 [--window ...]
"""
import argparse
import sys

DECL_ANCHOR = "    integer ::  met_nvars, nyears_spinup, nyears_trans, starti_site, endi_site"

INIT_ANCHOR = "          end do    !end variable loop"

PRE_ANCHOR = "            if (const_climate_hist .or. yr .le. atm2lnd_vars%startyear_met) then"

POST_ANCHOR = """            !if (yr .gt. atm2lnd_vars%startyear_met) then """

USE_ANCHOR = "        !Air temperature"


def decl_block(first_n, windows):
    lo = ", ".join(str(w[0]) for w in windows)
    hi = ", ".join(str(w[1]) for w in windows)
    return """    ! --- forcing diagnostic (SourceMods; generated by make_diag_sourcemod.py) ---
    integer, save :: diag_ncall = 0
    integer :: diag_ymd, diag_iw
    logical :: diag_on
    integer, parameter :: DIAG_FIRST_N = {first_n}
    integer, parameter :: DIAG_NWIN = {nwin}
    integer, parameter :: DIAG_WIN_LO(DIAG_NWIN) = (/ {lo} /)
    integer, parameter :: DIAG_WIN_HI(DIAG_NWIN) = (/ {hi} /)
    ! --- end forcing diagnostic ---
""".format(first_n=first_n, nwin=len(windows), lo=lo, hi=hi)


GATE_BLOCK = """
            ! --- forcing diagnostic: evaluate the gate once per (gridcell, call) ---
            ! Both insertion sites sit inside "do g = begg,endg / do v = 1,nvars",
            ! so the counter must advance once per call, not once per gridcell,
            ! and diag_on must be recomputed for every g (it is false for all
            ! but begg).  Counting per gridcell would exhaust DIAG_FIRST_N in
            ! the first timestep.
            if (v .eq. 1) then
              if (g .eq. bounds%begg) diag_ncall = diag_ncall + 1
              diag_on = masterproc .and. (g .eq. bounds%begg) .and. &
                        (diag_ncall .le. DIAG_FIRST_N)
              if (masterproc .and. (g .eq. bounds%begg)) then
                diag_ymd = yr*10000 + mon*100 + day
                do diag_iw = 1, DIAG_NWIN
                  if (diag_ymd .ge. DIAG_WIN_LO(diag_iw) .and. &
                      diag_ymd .le. DIAG_WIN_HI(diag_iw)) diag_on = .true.
                end do
              end if
            end if
            ! --- end forcing diagnostic ---
"""

INIT_BLOCK = """            ! --- forcing diagnostic ---
            if (diag_on) then
              write(iulog,'(a,i6,a,i3,1x,a8,a,i9,a,i3,a,i3,a,i6,a,i10,a,i10,a,i10,a,i10)') &
                'DIAG_INIT call=', diag_ncall, ' v=', v, trim(metvars(v)), &
                ' ymd=', yr*10000+mon*100+day, ' tod_h=', tod/3600, &
                ' npf=', nint(atm2lnd_vars%npf(v)), ' tres=', nint(atm2lnd_vars%timeres(v)), &
                ' t1=', atm2lnd_vars%tindex(g,v,1), ' t2=', atm2lnd_vars%tindex(g,v,2), &
                ' timelen=', atm2lnd_vars%timelen(v), ' tl_spinup=', atm2lnd_vars%timelen_spinup(v)
            end if
            ! --- end forcing diagnostic ---
"""

PRE_BLOCK = """            ! --- forcing diagnostic: index pair BEFORE the guard ---
            if (diag_on) then
              write(iulog,'(a,i6,a,i3,1x,a8,a,i9,a,i6,a,i10,a,i10)') &
                'DIAG_PRE  call=', diag_ncall, ' v=', v, trim(metvars(v)), &
                ' ymd=', yr*10000+mon*100+day, ' tod_h=', tod/3600, &
                ' t1=', atm2lnd_vars%tindex(g,v,1), ' t2=', atm2lnd_vars%tindex(g,v,2)
            end if
            ! --- end forcing diagnostic ---
"""

POST_BLOCK = """            ! --- forcing diagnostic: index pair AFTER the guard ---
            if (diag_on) then
              write(iulog,'(a,i6,a,i3,1x,a8,a,i10,a,i10,a,i10)') &
                'DIAG_POST call=', diag_ncall, ' v=', v, trim(metvars(v)), &
                ' t1=', atm2lnd_vars%tindex(g,v,1), ' t2=', atm2lnd_vars%tindex(g,v,2), &
                ' timelen=', atm2lnd_vars%timelen(v)
            end if
            ! --- end forcing diagnostic ---
"""

USE_BLOCK = """        ! --- forcing diagnostic: what was actually read and used ---
        if (diag_on) then
          write(iulog,'(a,i6,a,i8,a,i8,a,i8)') &
            'DIAG_CELL call=', diag_ncall, ' g=', g, ' begg=', bounds%begg, ' endg=', bounds%endg
          do diag_iw = 1, met_nvars
            write(iulog,'(a,i6,a,i3,1x,a8,a,i10,a,i10,a,i8,a,i8,a,es14.7,a,es14.7,a,es16.9,a,es16.9,a,f8.5,a,f8.5,a,es16.9)') &
              'DIAG_USE  call=', diag_ncall, ' v=', diag_iw, trim(metvars(diag_iw)), &
              ' t1=', tindex(diag_iw,1), ' t2=', tindex(diag_iw,2), &
              ' raw1=', atm2lnd_vars%atm_input(diag_iw,g,1,tindex(diag_iw,1)), &
              ' raw2=', atm2lnd_vars%atm_input(diag_iw,g,1,tindex(diag_iw,2)), &
              ' scale=', atm2lnd_vars%scale_factors(diag_iw), &
              ' offset=', atm2lnd_vars%add_offsets(diag_iw), &
              ' dec1=', atm2lnd_vars%atm_input(diag_iw,g,1,tindex(diag_iw,1))* &
                        atm2lnd_vars%scale_factors(diag_iw)+atm2lnd_vars%add_offsets(diag_iw), &
              ' dec2=', atm2lnd_vars%atm_input(diag_iw,g,1,tindex(diag_iw,2))* &
                        atm2lnd_vars%scale_factors(diag_iw)+atm2lnd_vars%add_offsets(diag_iw), &
              ' wt1=', wt1(diag_iw), ' wt2=', wt2(diag_iw), &
              ' used=', (atm2lnd_vars%atm_input(diag_iw,g,1,tindex(diag_iw,1))* &
                         atm2lnd_vars%scale_factors(diag_iw)+atm2lnd_vars%add_offsets(diag_iw))*wt1(diag_iw) + &
                        (atm2lnd_vars%atm_input(diag_iw,g,1,tindex(diag_iw,2))* &
                         atm2lnd_vars%scale_factors(diag_iw)+atm2lnd_vars%add_offsets(diag_iw))*wt2(diag_iw)
          end do
        end if
        ! --- end forcing diagnostic ---

"""


def insert_before(lines, anchor, block, label, expect=1):
    hits = [i for i, l in enumerate(lines) if l.rstrip() == anchor.rstrip()]
    if len(hits) != expect:
        sys.exit("ANCHOR %s: expected %d match(es), found %d -- refusing to write"
                 % (label, expect, len(hits)))
    out = []
    for i, l in enumerate(lines):
        if i in hits:
            out.extend(block.splitlines(True))
        out.append(l)
    return out


def parse_window(s):
    lo, hi = s.split("-")
    return int(lo), int(hi)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--src", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--first-n", type=int, default=24)
    p.add_argument("--window", action="append", default=[],
                   help="inclusive YYYYMMDD-YYYYMMDD, repeatable")
    a = p.parse_args()

    windows = [parse_window(w) for w in a.window] or [(0, 0)]
    lines = open(a.src).readlines()

    if any("forcing diagnostic" in l for l in lines):
        sys.exit("source already contains a diagnostic block -- refusing to double-patch")

    lines = insert_before(lines, DECL_ANCHOR, decl_block(a.first_n, windows), "DECL")
    # gate + INIT both go just before the end of the initialization variable loop
    lines = insert_before(lines, INIT_ANCHOR, GATE_BLOCK + INIT_BLOCK, "INIT")
    lines = insert_before(lines, PRE_ANCHOR, GATE_BLOCK + PRE_BLOCK, "PRE")
    lines = insert_before(lines, POST_ANCHOR, POST_BLOCK, "POST")
    lines = insert_before(lines, USE_ANCHOR, USE_BLOCK, "USE")

    with open(a.out, "w") as f:
        f.writelines(lines)
    print("wrote %s" % a.out)
    print("  first-n : %d import calls per process start" % a.first_n)
    print("  windows : %s" % windows)


if __name__ == "__main__":
    main()
